"""Adapter for the Ubuntu Security Notices (USN) RSS feed.

Ubuntu's feed (``https://ubuntu.com/security/notices/rss.xml``) is RSS 2.0
generated by Feedgen. Its channel carries ``copyright``, ``docs`` and
``generator`` fields, and each item's ``guid`` is the notice URL with an
``isPermaLink`` attribute (always ``false``). Descriptions are plain text
that inline the affected CVEs (e.g. ``(CVE-2026-33633)``).

The whole feed is security notices, so — unlike the F5 adapter — nothing is
filtered out: every USN is an advisory subscribers want. The plain-text
description is kept as-is; clean_summary() truncates it at embed time exactly
as it does for generic feedparser entries.
"""
import logging
import time
from dataclasses import dataclass, field
from email.utils import parsedate_to_datetime
from typing import ClassVar

log = logging.getLogger("adapters.ubuntu")


def _parse_pub_date(value: str) -> time.struct_time | None:
    """RFC 822 pubDate -> UTC struct_time (the shape feedparser produces)."""
    try:
        return parsedate_to_datetime(value).utctimetuple()
    except (TypeError, ValueError):
        return None


@dataclass
class UbuntuRSSItem:
    title: str
    link: str
    guid: str
    is_permalink: bool  # the guid element's isPermaLink attribute (always false)
    pub_date: str
    description: str  # plain text; inlines the affected CVEs

    def as_entry(self) -> dict:
        """Entry dict in the shape entry_key()/build_embed() expect."""
        return {
            "id": self.guid,
            "link": self.link,
            "title": self.title,
            "published": self.pub_date,
            "published_parsed": _parse_pub_date(self.pub_date),
            "summary": self.description,
        }


@dataclass
class UbuntuRSSFeed:
    feed_type: ClassVar[str] = "ubuntu"

    title: str
    link: str
    description: str
    language: str
    copyright: str
    generator: str
    docs: str
    items: list[UbuntuRSSItem] = field(default_factory=list)

    def entries(self) -> list[dict]:
        return [item.as_entry() for item in self.items]

    @classmethod
    def from_parsed(cls, parsed) -> "UbuntuRSSFeed":
        """Build from a feedparser result.

        feedparser renames the Ubuntu fields: copyright -> feed.rights,
        guid -> entry.id (its isPermaLink attribute -> entry.guidislink),
        pubDate -> entry.published, description -> entry.summary.
        """
        feed = parsed.feed
        return cls(
            title=feed.get("title", ""),
            link=feed.get("link", ""),
            description=feed.get("subtitle") or feed.get("description", ""),
            language=feed.get("language", ""),
            copyright=feed.get("rights") or feed.get("copyright", ""),
            generator=feed.get("generator", ""),
            docs=feed.get("docs", ""),
            items=[
                UbuntuRSSItem(
                    title=e.get("title", ""),
                    link=e.get("link", ""),
                    guid=e.get("id") or e.get("link", ""),
                    is_permalink=bool(e.get("guidislink", False)),
                    pub_date=e.get("published", ""),
                    description=e.get("summary", ""),
                )
                for e in parsed.entries
            ],
        )

    @classmethod
    def from_dict(cls, data: dict) -> "UbuntuRSSFeed":
        """Build from the raw object shape: {channel: {..., items: [...]}}.

        ``guid`` arrives as an object carrying the isPermaLink attribute;
        its text value (when present) sits under a value/#text key.
        """
        channel = data.get("channel", data)
        items = []
        for i in channel.get("items", []):
            guid = i.get("guid")
            if isinstance(guid, dict):
                is_permalink = bool(guid.get("isPermaLink", False))
                guid_value = guid.get("value") or guid.get("#text") or ""
            else:
                is_permalink = False
                guid_value = guid or ""
            items.append(
                UbuntuRSSItem(
                    title=i.get("title", ""),
                    link=i.get("link", ""),
                    guid=guid_value or i.get("link", ""),
                    is_permalink=is_permalink,
                    pub_date=i.get("pubDate", ""),
                    description=i.get("description", ""),
                )
            )
        return cls(
            title=channel.get("title", ""),
            link=channel.get("link", ""),
            description=channel.get("description", ""),
            language=channel.get("language", ""),
            copyright=channel.get("copyright", ""),
            generator=channel.get("generator", ""),
            docs=channel.get("docs", ""),
            items=items,
        )


ADAPTER = UbuntuRSSFeed
